### ISSUE TITLE
📌 Todo

### ISSUE THREAD

**Issue by Kirill-Shklyarenko** [Kirill-Shklyarenko/geoVision-API#1]
- [x] Gofiber Docker Dev Setup with Hot Reload
- [x] Swagger REST API documentation
- [x] Gorm (Golang SQL DB ORM) with Postgres - PostGIS implementation and auto migration
- [x] Configs via environmental variables
- [x] Logger
- [ ] User Auth functionality (Signup, Login, Forgot and Reset Password)
- [ ] JWT Authentication
- [ ] RESTFull API
- [ ] Improved Input Validations(could be better)
- [ ] Custom Error messages
- [ ] Email notification (Welcome email, Reset password email)
- [ ] Redis
- [ ] Unit tests

# maybe?

- [ ] SMS notification (2FA ,Reset password code)
